name: DocBuild

on:
  push:
    branches: master

defaults:
  run:
    shell: bash

jobs:
  build_docs:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version:  [3.8]
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          path: main
      - name: Check for documentation changes
        run: |
          cd main
          echo "LAST_COMMIT=$(echo `git log -1 --pretty=%B`)" >> $GITHUB_ENV
          echo "LAST_DOC_COMMIT=$(echo `git log -1 --pretty=%B docs`)" >> $GITHUB_ENV
          if [ "$LAST_COMMIT" != "$LAST_DOC_COMMIT" ]; then
            echo "No changes in documentation, skipping"
            exit 0
          fi
      - name: Install needed packages
        run: |
          pip3 install wheel
          pip3 install pytest
          sudo apt-get install python3-sphinx
          cd main/docs
          make html
      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: doc
      - name: Copy and commit changes
        run: |
          cp -r main/docs/build/html/* doc/dev
          cd doc
          git config user.name "Travis CI"
          git config user.email "pytest_order@gmail.com"
          git commit -a -m "$LAST_COMMIT"
          git push
